### ISSUE TITLE
Error with sourcecode

### ISSUE THREAD

**Issue by noorbakerally** [pyvandenbussche/lov#58]
This is an error i'm receiving when going on the route /dataset/lov/vocabs

/root/Applications/lov/app/controllers/search.js:585
        total_results: parsed.total,
                             ^
TypeError: Cannot read property 'total' of undefined
    at ElasticSearchCall.<anonymous> (/root/Applications/lov/app/controllers/search.js:585:30)
    at ElasticSearchCall.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/root/Applications/lov/node_modules/elasticsearchclient/lib/elasticsearchclient/calls/elasticSearchCall.js:66:22)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
[nodemon] app crashed - waiting for file changes before starting...

I tried to debug a little, by adding console.log(data) on line 577,  i got the following:
{"error":"IndexMissingException[[lov] missing]","status":404}:

**Comment by pyvandenbussche** [comment]
Hi,

LOV uses elasticsearch for listing and search trough vocabularies, agents, vocabulary elements. Have you run the script to build the full text index in elasticsearch? All scripts are located in https://github.com/pyvandenbussche/lovScripts project. After compiling this project you will have to run create-index script that will create the index in elasticsearch and then run index-lov that will populate the index.

**Comment by noorbakerally** [comment]
Hi, 
thanks for your help, and as soon as i manage to deploy the app successfully, i'll write a comprehensive wiki to describe the process,

the scripts, i've already build it, but i've run none of them manually, i'm seeing that the app are calling them, 

is there any scripts that I should run manually ?

**Comment by noorbakerally** [comment]
Hi, i'm sorry for troubling and thank you for your help, I'm going to write a wiki to document the process and also I'm working on a docker image which I will make public,

the scripts i have run is good, now I'm not getting the error, but i'm getting the same error when going on the url http://domainname.com/dataset/lov/terms

/root/Applications/lov/app/controllers/search.js:434
        total_results: parsed.total,
                             ^
TypeError: Cannot read property 'total' of undefined
    at ElasticSearchCall.<anonymous> (/root/Applications/lov/app/controllers/search.js:434:30)
    at ElasticSearchCall.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/root/Applications/lov/node_modules/elasticsearchclient/lib/elasticsearchclient/calls/elasticSearchCall.js:66:22)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by gatemezing** [comment]
@noorbakerally Any update on this issue? TIA
